// GENERATED BY VELTRO — DO NOT EDIT
part of 'audit_log.dart';

mixin _$AuditLog {
  String get id;
  int get timestamp;
  Device get device;
  String? get action;
  bool? get success;
  int? get durationMs;

  AuditLog copyWith({String? id, int? timestamp, Device? device, String? action, bool? success, int? durationMs, });
  Map<String, dynamic> toJson();

  @override
  String toString();
}

class _AuditLog with _$AuditLog implements AuditLog {
  @override final String id;
  @override final int timestamp;
  @override final Device device;
  @override final String? action;
  @override final bool? success;
  @override final int? durationMs;

  const _AuditLog({
    required this.id,
    required this.timestamp,
    required this.device,
    this.action,
    this.success,
    this.durationMs,
  });

  factory _AuditLog.fromJson(Map<String, dynamic> json) => _AuditLog(
    id: json['id'] as String,
    timestamp: json['timestamp'] as int,
    device: Device.fromJson(json['device'] as Map<String, dynamic>),
    action: json['action'] as String?,
    success: json['success'] as bool?,
    durationMs: json['durationMs'] as int?,
  );

  @override
  AuditLog copyWith({
    String? id,
    int? timestamp,
    Device? device,
    String? action,
    bool? success,
    int? durationMs,
  }) => _AuditLog(
    id: id ?? this.id,
    timestamp: timestamp ?? this.timestamp,
    device: device ?? this.device,
    action: action ?? this.action,
    success: success ?? this.success,
    durationMs: durationMs ?? this.durationMs,
  );

  @override
  Map<String, dynamic> toJson() => {
    'id': id,
    'timestamp': timestamp,
    'device': device.toJson(),
    'action': action,
    'success': success,
    'durationMs': durationMs,
  };

  @override
  bool operator ==(Object other) =>
    identical(this, other) ||
    (other is _AuditLog && other.id == id && other.timestamp == timestamp && other.device == device && other.action == action && other.success == success && other.durationMs == durationMs);

  @override
  int get hashCode => Object.hashAll([id, timestamp, device, action, success, durationMs]);

  @override
  String toString() => 'AuditLog(id: $id, timestamp: $timestamp, device: $device, action: $action, success: $success, durationMs: $durationMs)';
}

extension _$AuditLogJsonExtension on AuditLog {
  // ignore: unused_element
  static AuditLog fromJson(Map<String, dynamic> json) =>
      _AuditLog.fromJson(json);
}
