// GENERATED BY VELTRO — DO NOT EDIT
part of 'device.dart';

mixin _$Device {
  String get deviceId;
  DeviceType get type;
  Address get address;
  String? get osVersion;
  bool? get isActive;

  Device copyWith({String? deviceId, DeviceType? type, Address? address, String? osVersion, bool? isActive, });
  Map<String, dynamic> toJson();

  @override
  String toString();
}

class _Device with _$Device implements Device {
  @override final String deviceId;
  @override final DeviceType type;
  @override final Address address;
  @override final String? osVersion;
  @override final bool? isActive;

  const _Device({
    required this.deviceId,
    required this.type,
    required this.address,
    this.osVersion,
    this.isActive,
  });

  factory _Device.fromJson(Map<String, dynamic> json) => _Device(
    deviceId: json['deviceId'] as String,
    type: DeviceType.values.byName(json['type'] as String),
    address: Address.fromJson(json['address'] as Map<String, dynamic>),
    osVersion: json['osVersion'] as String?,
    isActive: json['isActive'] as bool?,
  );

  @override
  Device copyWith({
    String? deviceId,
    DeviceType? type,
    Address? address,
    String? osVersion,
    bool? isActive,
  }) => _Device(
    deviceId: deviceId ?? this.deviceId,
    type: type ?? this.type,
    address: address ?? this.address,
    osVersion: osVersion ?? this.osVersion,
    isActive: isActive ?? this.isActive,
  );

  @override
  Map<String, dynamic> toJson() => {
    'deviceId': deviceId,
    'type': type.name,
    'address': address.toJson(),
    'osVersion': osVersion,
    'isActive': isActive,
  };

  @override
  bool operator ==(Object other) =>
    identical(this, other) ||
    (other is _Device && other.deviceId == deviceId && other.type == type && other.address == address && other.osVersion == osVersion && other.isActive == isActive);

  @override
  int get hashCode => Object.hashAll([deviceId, type, address, osVersion, isActive]);

  @override
  String toString() => 'Device(deviceId: $deviceId, type: $type, address: $address, osVersion: $osVersion, isActive: $isActive)';
}

extension _$DeviceJsonExtension on Device {
  // ignore: unused_element
  static Device fromJson(Map<String, dynamic> json) =>
      _Device.fromJson(json);
}
