use crate::ir::{DataClassIR, FieldIR, TypeKind};

/// Generates Dart code for a set of DataClassIRs belonging to the same source file.
pub fn generate(ir_list: &[DataClassIR]) -> String {
    if ir_list.is_empty() {
        return String::new();
    }

    let mut code = String::new();

    // 1. Header comment
    code.push_str("// GENERATED BY VELTRO — DO NOT EDIT\n");

    // 2. part of directive (use the first IR's source file)
    let file_name = ir_list[0].source_file.file_name()
        .and_then(|s| s.to_str())
        .unwrap_or("unknown.dart");
    code.push_str(&format!("part of '{}';\n", file_name));

    for ir in ir_list {
        code.push('\n');
        let generics_decl = if ir.generics.is_empty() {
            "".to_string()
        } else {
            format!("<{}>", ir.generics.join(", "))
        };

        // 3. _ClassName concrete class
        code.push_str(&format!("class _{}{} extends {}{} {{\n", ir.name, generics_decl, ir.name, generics_decl));

        // Fields
        for field in &ir.fields {
            let type_str = get_type_string(field);
            code.push_str(&format!("  final {} {};\n", type_str, field.name));
        }
        code.push('\n');

        // 4. Constructor
        code.push_str(&format!("  const _{}({{\n", ir.name));
        for field in &ir.fields {
            let required = if field.is_required { "required " } else { "" };
            code.push_str(&format!("    {}this.{},\n", required, field.name));
        }
        code.push_str("  });\n\n");

        // 5. fromJson factory
        let from_json_params = if ir.generics.is_empty() {
            "".to_string()
        } else {
            ir.generics
                .iter()
                .map(|g| format!(", {} Function(Object?) fromJson{}", g, g))
                .collect::<Vec<_>>()
                .join("")
        };

        code.push_str(&format!("  factory _{}.fromJson(Map<String, dynamic> json{}) {{\n", ir.name, from_json_params));
        code.push_str(&format!("    return _{}(\n", ir.name));
        for field in &ir.fields {
            let line = generate_from_json_field(field);
            code.push_str(&format!("      {},\n", line));
        }
        code.push_str("    );\n");
        code.push_str("  }\n\n");

        // 6. toJson method
        code.push_str("  @override\n  Map<String, dynamic> toJson() {\n");
        code.push_str("    return {\n");
        for field in &ir.fields {
            let val = match field.resolved_kind {
                TypeKind::DataClass | TypeKind::Enum => format!("{}.toJson()", field.name),
                _ => field.name.clone(),
            };
            code.push_str(&format!("      '{}': {},\n", field.name, val));
        }
        code.push_str("    };\n");
        code.push_str("  }\n\n");

        // 7. copyWith method
        code.push_str(&format!("  @override\n  _{}{} copyWith({{\n", ir.name, generics_decl));
        for field in &ir.fields {
            let type_str = get_type_string(field);
            let type_name_no_q = type_str.trim_end_matches('?');
            code.push_str(&format!("    {}? {},\n", type_name_no_q, field.name));
        }
        code.push_str("  }) {\n");
        code.push_str(&format!("    return _{}(\n", ir.name));
        for field in &ir.fields {
            code.push_str(&format!("      {}: {} ?? this.{},\n", field.name, field.name, field.name));
        }
        code.push_str("    );\n");
        code.push_str("  }\n\n");

        // 8. operator ==
        code.push_str("  @override\n  bool operator ==(Object other) {\n");
        code.push_str(&format!("    return identical(this, other) || (other is _{}{} && \n", ir.name, generics_decl));
        let comparisons: Vec<String> = ir.fields.iter().map(|f| format!("other.{} == {}", f.name, f.name)).collect();
        code.push_str(&format!("      {});\n", comparisons.join(" && ")));
        code.push_str("  }\n\n");

        // 9. hashCode
        code.push_str("  @override\n  int get hashCode => Object.hashAll([\n");
        for field in &ir.fields {
            code.push_str(&format!("    {},\n", field.name));
        }
        code.push_str("  ]);\n\n");

        // 10. toString
        code.push_str("  @override\n  String toString() {\n");
        let fields_str: Vec<String> = ir.fields.iter().map(|f| format!("{}: ${{{}}}", f.name, f.name)).collect();
        code.push_str(&format!("    return '{}({})';\n", ir.name, fields_str.join(", ")));
        code.push_str("  }\n");
        code.push_str("}\n");

        // Top-level helper for fromJson
        code.push_str(&format!("\n{}{} _${}FromJson{}(Map<String, dynamic> json{}) {{\n", 
            ir.name, generics_decl, ir.name, generics_decl, from_json_params));
        let args = if ir.generics.is_empty() {
            "".to_string()
        } else {
            ir.generics.iter().map(|g| format!(", fromJson{}", g)).collect::<Vec<_>>().join("")
        };
        code.push_str(&format!("  return _{}.fromJson(json{});\n", ir.name, args));
        code.push_str("}\n");
    }

    code
}

fn get_type_string(field: &FieldIR) -> String {
    let mut s = field.type_name.clone();
    if !field.generic_args.is_empty() {
        s.push_str(&format!("<{}>", field.generic_args.join(", ")));
    }
    if field.is_nullable {
        s.push('?');
    }
    s
}

fn generate_from_json_field(field: &FieldIR) -> String {
    if field.is_generic_param {
        return format!("{}: fromJson{}(json['{}'])", field.name, field.type_name, field.name);
    }

    match field.resolved_kind {
        TypeKind::DataClass => format!(
            "{}: {}.fromJson(json['{}'] as Map<String, dynamic>)",
            field.name, field.type_name, field.name
        ),
        TypeKind::Enum => format!(
            "{}: {}Extension.fromJson(json['{}'] as String)",
            field.name, field.type_name, field.name
        ),
        TypeKind::External => {
            let type_str = get_type_string(field);
            format!(
                "{}: json['{}'] as {}",
                field.name, field.name, type_str
            )
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::{DataClassIR, FieldIR, TypeKind};
    use std::path::PathBuf;

    #[test]
    fn test_generate_simple() {
        let ir = DataClassIR {
            name: "User".to_string(),
            generics: vec![],
            fields: vec![
                FieldIR {
                    name: "id".to_string(),
                    type_name: "String".to_string(),
                    generic_args: vec![],
                    is_required: true,
                    is_nullable: false,
                    resolved_kind: TypeKind::External,
                    is_generic_param: false,
                },
            ],
            source_file: PathBuf::from("user.dart"),
        };
        
        let output = generate(&[ir]);
        assert!(output.contains("class _User extends User"));
        assert!(output.contains("id: json['id'] as String"));
    }
}
