// GENERATED BY VELTRO — DO NOT EDIT
part of 'address.dart';

mixin _$Address {
  String get street;
  String get city;
  String get country;

  Address copyWith({String? street, String? city, String? country, });
  Map<String, dynamic> toJson();

  @override
  String toString();
}

class _Address with _$Address implements Address {
  @override final String street;
  @override final String city;
  @override final String country;

  const _Address({
    required this.street,
    required this.city,
    required this.country,
  });

  factory _Address.fromJson(Map<String, dynamic> json) => _Address(
    street: json['street'] as String,
    city: json['city'] as String,
    country: json['country'] as String,
  );

  @override
  Address copyWith({
    String? street,
    String? city,
    String? country,
  }) => _Address(
    street: street ?? this.street,
    city: city ?? this.city,
    country: country ?? this.country,
  );

  @override
  Map<String, dynamic> toJson() => {
    'street': street,
    'city': city,
    'country': country,
  };

  @override
  bool operator ==(Object other) =>
    identical(this, other) ||
    (other is _Address && other.street == street && other.city == city && other.country == country);

  @override
  int get hashCode => Object.hashAll([street, city, country]);

  @override
  String toString() => 'Address(street: $street, city: $city, country: $country)';
}

extension _$AddressJsonExtension on Address {
  // ignore: unused_element
  static Address fromJson(Map<String, dynamic> json) =>
      _Address.fromJson(json);
}
