// GENERATED BY VELTRO — DO NOT EDIT
part of 'api_response.dart';

mixin _$ApiResponse<T> {
  bool get success;
  T get data;
  String get message;

  ApiResponse<T> copyWith({bool? success, T? data, String? message, });
  Map<String, dynamic> toJson();

  @override
  String toString();
}

class _ApiResponse<T> with _$ApiResponse<T> implements ApiResponse<T> {
  @override final bool success;
  @override final T data;
  @override final String message;

  const _ApiResponse({
    required this.success,
    required this.data,
    required this.message,
  });

  factory _ApiResponse.fromJson(Map<String, dynamic> json, T Function(Object?) fromJsonT) => _ApiResponse(
    success: json['success'] as bool,
    data: fromJsonT(json['data']),
    message: json['message'] as String,
  );

  @override
  ApiResponse<T> copyWith({
    bool? success,
    T? data,
    String? message,
  }) => _ApiResponse(
    success: success ?? this.success,
    data: data ?? this.data,
    message: message ?? this.message,
  );

  @override
  Map<String, dynamic> toJson() => {
    'success': success,
    'data': data,
    'message': message,
  };

  @override
  bool operator ==(Object other) =>
    identical(this, other) ||
    (other is _ApiResponse<T> && other.success == success && other.data == data && other.message == message);

  @override
  int get hashCode => Object.hashAll([success, data, message]);

  @override
  String toString() => 'ApiResponse(success: $success, data: $data, message: $message)';
}

ApiResponse<T> _$ApiResponseFromJson<T>(Map<String, dynamic> json, T Function(Object?) fromJsonT) =>
  _ApiResponse.fromJson(json, fromJsonT);
