// GENERATED BY VELTRO — DO NOT EDIT
part of 'large_record.dart';

mixin _$LargeRecord {
  String get id;
  int get age;
  bool get isActive;
  double get score;
  Address get home;
  Status get status;
  Role get role;
  User get owner;
  String? get nickname;
  int? get optionalAge;
  bool? get optionalFlag;
  double? get optionalScore;
  String get s0;
  String get s1;
  String get s2;
  String get s3;
  String get s4;
  String get s5;
  String get s6;
  String get s7;
  String get s8;
  String get s9;
  String get s10;
  String get s11;
  String get s12;
  String get s13;
  String get s14;
  String get s15;
  String get s16;
  String get s17;
  String get s18;
  String get s19;
  int get i0;
  int get i1;
  int get i2;
  int get i3;
  int get i4;
  int get i5;
  int get i6;
  int get i7;
  int get i8;
  int get i9;
  bool get b0;
  bool get b1;
  bool get b2;
  bool get b3;
  bool get b4;
  double get d0;
  double get d1;
  double get d2;
  double get d3;
  double get d4;

  LargeRecord copyWith({String? id, int? age, bool? isActive, double? score, Address? home, Status? status, Role? role, User? owner, String? nickname, int? optionalAge, bool? optionalFlag, double? optionalScore, String? s0, String? s1, String? s2, String? s3, String? s4, String? s5, String? s6, String? s7, String? s8, String? s9, String? s10, String? s11, String? s12, String? s13, String? s14, String? s15, String? s16, String? s17, String? s18, String? s19, int? i0, int? i1, int? i2, int? i3, int? i4, int? i5, int? i6, int? i7, int? i8, int? i9, bool? b0, bool? b1, bool? b2, bool? b3, bool? b4, double? d0, double? d1, double? d2, double? d3, double? d4, });
  Map<String, dynamic> toJson();

  @override
  String toString();
}

class _LargeRecord with _$LargeRecord implements LargeRecord {
  @override final String id;
  @override final int age;
  @override final bool isActive;
  @override final double score;
  @override final Address home;
  @override final Status status;
  @override final Role role;
  @override final User owner;
  @override final String? nickname;
  @override final int? optionalAge;
  @override final bool? optionalFlag;
  @override final double? optionalScore;
  @override final String s0;
  @override final String s1;
  @override final String s2;
  @override final String s3;
  @override final String s4;
  @override final String s5;
  @override final String s6;
  @override final String s7;
  @override final String s8;
  @override final String s9;
  @override final String s10;
  @override final String s11;
  @override final String s12;
  @override final String s13;
  @override final String s14;
  @override final String s15;
  @override final String s16;
  @override final String s17;
  @override final String s18;
  @override final String s19;
  @override final int i0;
  @override final int i1;
  @override final int i2;
  @override final int i3;
  @override final int i4;
  @override final int i5;
  @override final int i6;
  @override final int i7;
  @override final int i8;
  @override final int i9;
  @override final bool b0;
  @override final bool b1;
  @override final bool b2;
  @override final bool b3;
  @override final bool b4;
  @override final double d0;
  @override final double d1;
  @override final double d2;
  @override final double d3;
  @override final double d4;

  const _LargeRecord({
    required this.id,
    required this.age,
    required this.isActive,
    required this.score,
    required this.home,
    required this.status,
    required this.role,
    required this.owner,
    this.nickname,
    this.optionalAge,
    this.optionalFlag,
    this.optionalScore,
    required this.s0,
    required this.s1,
    required this.s2,
    required this.s3,
    required this.s4,
    required this.s5,
    required this.s6,
    required this.s7,
    required this.s8,
    required this.s9,
    required this.s10,
    required this.s11,
    required this.s12,
    required this.s13,
    required this.s14,
    required this.s15,
    required this.s16,
    required this.s17,
    required this.s18,
    required this.s19,
    required this.i0,
    required this.i1,
    required this.i2,
    required this.i3,
    required this.i4,
    required this.i5,
    required this.i6,
    required this.i7,
    required this.i8,
    required this.i9,
    required this.b0,
    required this.b1,
    required this.b2,
    required this.b3,
    required this.b4,
    required this.d0,
    required this.d1,
    required this.d2,
    required this.d3,
    required this.d4,
  });

  factory _LargeRecord.fromJson(Map<String, dynamic> json) => _LargeRecord(
    id: json['id'] as String,
    age: json['age'] as int,
    isActive: json['isActive'] as bool,
    score: json['score'] as double,
    home: Address.fromJson(json['home'] as Map<String, dynamic>),
    status: Status.values.byName(json['status'] as String),
    role: Role.values.byName(json['role'] as String),
    owner: User.fromJson(json['owner'] as Map<String, dynamic>),
    nickname: json['nickname'] as String?,
    optionalAge: json['optionalAge'] as int?,
    optionalFlag: json['optionalFlag'] as bool?,
    optionalScore: json['optionalScore'] as double?,
    s0: json['s0'] as String,
    s1: json['s1'] as String,
    s2: json['s2'] as String,
    s3: json['s3'] as String,
    s4: json['s4'] as String,
    s5: json['s5'] as String,
    s6: json['s6'] as String,
    s7: json['s7'] as String,
    s8: json['s8'] as String,
    s9: json['s9'] as String,
    s10: json['s10'] as String,
    s11: json['s11'] as String,
    s12: json['s12'] as String,
    s13: json['s13'] as String,
    s14: json['s14'] as String,
    s15: json['s15'] as String,
    s16: json['s16'] as String,
    s17: json['s17'] as String,
    s18: json['s18'] as String,
    s19: json['s19'] as String,
    i0: json['i0'] as int,
    i1: json['i1'] as int,
    i2: json['i2'] as int,
    i3: json['i3'] as int,
    i4: json['i4'] as int,
    i5: json['i5'] as int,
    i6: json['i6'] as int,
    i7: json['i7'] as int,
    i8: json['i8'] as int,
    i9: json['i9'] as int,
    b0: json['b0'] as bool,
    b1: json['b1'] as bool,
    b2: json['b2'] as bool,
    b3: json['b3'] as bool,
    b4: json['b4'] as bool,
    d0: json['d0'] as double,
    d1: json['d1'] as double,
    d2: json['d2'] as double,
    d3: json['d3'] as double,
    d4: json['d4'] as double,
  );

  @override
  LargeRecord copyWith({
    String? id,
    int? age,
    bool? isActive,
    double? score,
    Address? home,
    Status? status,
    Role? role,
    User? owner,
    String? nickname,
    int? optionalAge,
    bool? optionalFlag,
    double? optionalScore,
    String? s0,
    String? s1,
    String? s2,
    String? s3,
    String? s4,
    String? s5,
    String? s6,
    String? s7,
    String? s8,
    String? s9,
    String? s10,
    String? s11,
    String? s12,
    String? s13,
    String? s14,
    String? s15,
    String? s16,
    String? s17,
    String? s18,
    String? s19,
    int? i0,
    int? i1,
    int? i2,
    int? i3,
    int? i4,
    int? i5,
    int? i6,
    int? i7,
    int? i8,
    int? i9,
    bool? b0,
    bool? b1,
    bool? b2,
    bool? b3,
    bool? b4,
    double? d0,
    double? d1,
    double? d2,
    double? d3,
    double? d4,
  }) => _LargeRecord(
    id: id ?? this.id,
    age: age ?? this.age,
    isActive: isActive ?? this.isActive,
    score: score ?? this.score,
    home: home ?? this.home,
    status: status ?? this.status,
    role: role ?? this.role,
    owner: owner ?? this.owner,
    nickname: nickname ?? this.nickname,
    optionalAge: optionalAge ?? this.optionalAge,
    optionalFlag: optionalFlag ?? this.optionalFlag,
    optionalScore: optionalScore ?? this.optionalScore,
    s0: s0 ?? this.s0,
    s1: s1 ?? this.s1,
    s2: s2 ?? this.s2,
    s3: s3 ?? this.s3,
    s4: s4 ?? this.s4,
    s5: s5 ?? this.s5,
    s6: s6 ?? this.s6,
    s7: s7 ?? this.s7,
    s8: s8 ?? this.s8,
    s9: s9 ?? this.s9,
    s10: s10 ?? this.s10,
    s11: s11 ?? this.s11,
    s12: s12 ?? this.s12,
    s13: s13 ?? this.s13,
    s14: s14 ?? this.s14,
    s15: s15 ?? this.s15,
    s16: s16 ?? this.s16,
    s17: s17 ?? this.s17,
    s18: s18 ?? this.s18,
    s19: s19 ?? this.s19,
    i0: i0 ?? this.i0,
    i1: i1 ?? this.i1,
    i2: i2 ?? this.i2,
    i3: i3 ?? this.i3,
    i4: i4 ?? this.i4,
    i5: i5 ?? this.i5,
    i6: i6 ?? this.i6,
    i7: i7 ?? this.i7,
    i8: i8 ?? this.i8,
    i9: i9 ?? this.i9,
    b0: b0 ?? this.b0,
    b1: b1 ?? this.b1,
    b2: b2 ?? this.b2,
    b3: b3 ?? this.b3,
    b4: b4 ?? this.b4,
    d0: d0 ?? this.d0,
    d1: d1 ?? this.d1,
    d2: d2 ?? this.d2,
    d3: d3 ?? this.d3,
    d4: d4 ?? this.d4,
  );

  @override
  Map<String, dynamic> toJson() => {
    'id': id,
    'age': age,
    'isActive': isActive,
    'score': score,
    'home': home.toJson(),
    'status': status.name,
    'role': role.name,
    'owner': owner.toJson(),
    'nickname': nickname,
    'optionalAge': optionalAge,
    'optionalFlag': optionalFlag,
    'optionalScore': optionalScore,
    's0': s0,
    's1': s1,
    's2': s2,
    's3': s3,
    's4': s4,
    's5': s5,
    's6': s6,
    's7': s7,
    's8': s8,
    's9': s9,
    's10': s10,
    's11': s11,
    's12': s12,
    's13': s13,
    's14': s14,
    's15': s15,
    's16': s16,
    's17': s17,
    's18': s18,
    's19': s19,
    'i0': i0,
    'i1': i1,
    'i2': i2,
    'i3': i3,
    'i4': i4,
    'i5': i5,
    'i6': i6,
    'i7': i7,
    'i8': i8,
    'i9': i9,
    'b0': b0,
    'b1': b1,
    'b2': b2,
    'b3': b3,
    'b4': b4,
    'd0': d0,
    'd1': d1,
    'd2': d2,
    'd3': d3,
    'd4': d4,
  };

  @override
  bool operator ==(Object other) =>
    identical(this, other) ||
    (other is _LargeRecord && other.id == id && other.age == age && other.isActive == isActive && other.score == score && other.home == home && other.status == status && other.role == role && other.owner == owner && other.nickname == nickname && other.optionalAge == optionalAge && other.optionalFlag == optionalFlag && other.optionalScore == optionalScore && other.s0 == s0 && other.s1 == s1 && other.s2 == s2 && other.s3 == s3 && other.s4 == s4 && other.s5 == s5 && other.s6 == s6 && other.s7 == s7 && other.s8 == s8 && other.s9 == s9 && other.s10 == s10 && other.s11 == s11 && other.s12 == s12 && other.s13 == s13 && other.s14 == s14 && other.s15 == s15 && other.s16 == s16 && other.s17 == s17 && other.s18 == s18 && other.s19 == s19 && other.i0 == i0 && other.i1 == i1 && other.i2 == i2 && other.i3 == i3 && other.i4 == i4 && other.i5 == i5 && other.i6 == i6 && other.i7 == i7 && other.i8 == i8 && other.i9 == i9 && other.b0 == b0 && other.b1 == b1 && other.b2 == b2 && other.b3 == b3 && other.b4 == b4 && other.d0 == d0 && other.d1 == d1 && other.d2 == d2 && other.d3 == d3 && other.d4 == d4);

  @override
  int get hashCode => Object.hashAll([id, age, isActive, score, home, status, role, owner, nickname, optionalAge, optionalFlag, optionalScore, s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15, s16, s17, s18, s19, i0, i1, i2, i3, i4, i5, i6, i7, i8, i9, b0, b1, b2, b3, b4, d0, d1, d2, d3, d4]);

  @override
  String toString() => 'LargeRecord(id: $id, age: $age, isActive: $isActive, score: $score, home: $home, status: $status, role: $role, owner: $owner, nickname: $nickname, optionalAge: $optionalAge, optionalFlag: $optionalFlag, optionalScore: $optionalScore, s0: $s0, s1: $s1, s2: $s2, s3: $s3, s4: $s4, s5: $s5, s6: $s6, s7: $s7, s8: $s8, s9: $s9, s10: $s10, s11: $s11, s12: $s12, s13: $s13, s14: $s14, s15: $s15, s16: $s16, s17: $s17, s18: $s18, s19: $s19, i0: $i0, i1: $i1, i2: $i2, i3: $i3, i4: $i4, i5: $i5, i6: $i6, i7: $i7, i8: $i8, i9: $i9, b0: $b0, b1: $b1, b2: $b2, b3: $b3, b4: $b4, d0: $d0, d1: $d1, d2: $d2, d3: $d3, d4: $d4)';
}

extension _$LargeRecordJsonExtension on LargeRecord {
  // ignore: unused_element
  static LargeRecord fromJson(Map<String, dynamic> json) =>
      _LargeRecord.fromJson(json);
}
