// GENERATED BY VELTRO — DO NOT EDIT
part of 'nullable_profile.dart';

mixin _$NullableProfile {
  User get user;
  Status get status;
  Role get role;
  Address get location;
  String? get website;
  int? get followers;
  bool? get marketingOptIn;

  NullableProfile copyWith({User? user, Status? status, Role? role, Address? location, String? website, int? followers, bool? marketingOptIn, });
  Map<String, dynamic> toJson();

  @override
  String toString();
}

class _NullableProfile with _$NullableProfile implements NullableProfile {
  @override final User user;
  @override final Status status;
  @override final Role role;
  @override final Address location;
  @override final String? website;
  @override final int? followers;
  @override final bool? marketingOptIn;

  const _NullableProfile({
    required this.user,
    required this.status,
    required this.role,
    required this.location,
    this.website,
    this.followers,
    this.marketingOptIn,
  });

  factory _NullableProfile.fromJson(Map<String, dynamic> json) => _NullableProfile(
    user: User.fromJson(json['user'] as Map<String, dynamic>),
    status: Status.values.byName(json['status'] as String),
    role: Role.values.byName(json['role'] as String),
    location: Address.fromJson(json['location'] as Map<String, dynamic>),
    website: json['website'] as String?,
    followers: json['followers'] as int?,
    marketingOptIn: json['marketingOptIn'] as bool?,
  );

  @override
  NullableProfile copyWith({
    User? user,
    Status? status,
    Role? role,
    Address? location,
    String? website,
    int? followers,
    bool? marketingOptIn,
  }) => _NullableProfile(
    user: user ?? this.user,
    status: status ?? this.status,
    role: role ?? this.role,
    location: location ?? this.location,
    website: website ?? this.website,
    followers: followers ?? this.followers,
    marketingOptIn: marketingOptIn ?? this.marketingOptIn,
  );

  @override
  Map<String, dynamic> toJson() => {
    'user': user.toJson(),
    'status': status.name,
    'role': role.name,
    'location': location.toJson(),
    'website': website,
    'followers': followers,
    'marketingOptIn': marketingOptIn,
  };

  @override
  bool operator ==(Object other) =>
    identical(this, other) ||
    (other is _NullableProfile && other.user == user && other.status == status && other.role == role && other.location == location && other.website == website && other.followers == followers && other.marketingOptIn == marketingOptIn);

  @override
  int get hashCode => Object.hashAll([user, status, role, location, website, followers, marketingOptIn]);

  @override
  String toString() => 'NullableProfile(user: $user, status: $status, role: $role, location: $location, website: $website, followers: $followers, marketingOptIn: $marketingOptIn)';
}

extension _$NullableProfileJsonExtension on NullableProfile {
  // ignore: unused_element
  static NullableProfile fromJson(Map<String, dynamic> json) =>
      _NullableProfile.fromJson(json);
}
