// GENERATED BY VELTRO — DO NOT EDIT
part of 'user.dart';

mixin _$User {
  String get id;
  String get name;
  int get age;
  bool get isVerified;
  Address get address;
  Status get status;

  User copyWith({String? id, String? name, int? age, bool? isVerified, Address? address, Status? status, });
  Map<String, dynamic> toJson();

  @override
  String toString();
}

class _User with _$User implements User {
  @override final String id;
  @override final String name;
  @override final int age;
  @override final bool isVerified;
  @override final Address address;
  @override final Status status;

  const _User({
    required this.id,
    required this.name,
    required this.age,
    required this.isVerified,
    required this.address,
    required this.status,
  });

  factory _User.fromJson(Map<String, dynamic> json) => _User(
    id: json['id'] as String,
    name: json['name'] as String,
    age: json['age'] as int,
    isVerified: json['isVerified'] as bool,
    address: Address.fromJson(json['address'] as Map<String, dynamic>),
    status: Status.values.byName(json['status'] as String),
  );

  @override
  User copyWith({
    String? id,
    String? name,
    int? age,
    bool? isVerified,
    Address? address,
    Status? status,
  }) => _User(
    id: id ?? this.id,
    name: name ?? this.name,
    age: age ?? this.age,
    isVerified: isVerified ?? this.isVerified,
    address: address ?? this.address,
    status: status ?? this.status,
  );

  @override
  Map<String, dynamic> toJson() => {
    'id': id,
    'name': name,
    'age': age,
    'isVerified': isVerified,
    'address': address.toJson(),
    'status': status.name,
  };

  @override
  bool operator ==(Object other) =>
    identical(this, other) ||
    (other is _User && other.id == id && other.name == name && other.age == age && other.isVerified == isVerified && other.address == address && other.status == status);

  @override
  int get hashCode => Object.hashAll([id, name, age, isVerified, address, status]);

  @override
  String toString() => 'User(id: $id, name: $name, age: $age, isVerified: $isVerified, address: $address, status: $status)';
}

extension _$UserJsonExtension on User {
  // ignore: unused_element
  static User fromJson(Map<String, dynamic> json) =>
      _User.fromJson(json);
}
