// GENERATED BY VELTRO — DO NOT EDIT
part of 'user_state_loading.dart';

mixin _$UserStateLoading {
  bool get isLoading;
  String? get message;

  UserStateLoading copyWith({bool? isLoading, String? message, });
  Map<String, dynamic> toJson();

  @override
  String toString();
}

class _UserStateLoading with _$UserStateLoading implements UserStateLoading {
  @override final bool isLoading;
  @override final String? message;

  const _UserStateLoading({
    required this.isLoading,
    this.message,
  });

  factory _UserStateLoading.fromJson(Map<String, dynamic> json) => _UserStateLoading(
    isLoading: json['isLoading'] as bool,
    message: json['message'] as String?,
  );

  @override
  UserStateLoading copyWith({
    bool? isLoading,
    String? message,
  }) => _UserStateLoading(
    isLoading: isLoading ?? this.isLoading,
    message: message ?? this.message,
  );

  @override
  Map<String, dynamic> toJson() => {
    'isLoading': isLoading,
    'message': message,
  };

  @override
  bool operator ==(Object other) =>
    identical(this, other) ||
    (other is _UserStateLoading && other.isLoading == isLoading && other.message == message);

  @override
  int get hashCode => Object.hashAll([isLoading, message]);

  @override
  String toString() => 'UserStateLoading(isLoading: $isLoading, message: $message)';
}

extension _$UserStateLoadingJsonExtension on UserStateLoading {
  // ignore: unused_element
  static UserStateLoading fromJson(Map<String, dynamic> json) =>
      _UserStateLoading.fromJson(json);
}
