// GENERATED BY VELTRO — DO NOT EDIT
part of 'user_state_loaded.dart';

mixin _$UserStateLoaded {
  User get user;
  Address get lastKnownAddress;
  Role get role;
  Status get status;

  UserStateLoaded copyWith({User? user, Address? lastKnownAddress, Role? role, Status? status, });
  Map<String, dynamic> toJson();

  @override
  String toString();
}

class _UserStateLoaded with _$UserStateLoaded implements UserStateLoaded {
  @override final User user;
  @override final Address lastKnownAddress;
  @override final Role role;
  @override final Status status;

  const _UserStateLoaded({
    required this.user,
    required this.lastKnownAddress,
    required this.role,
    required this.status,
  });

  factory _UserStateLoaded.fromJson(Map<String, dynamic> json) => _UserStateLoaded(
    user: User.fromJson(json['user'] as Map<String, dynamic>),
    lastKnownAddress: Address.fromJson(json['lastKnownAddress'] as Map<String, dynamic>),
    role: Role.values.byName(json['role'] as String),
    status: Status.values.byName(json['status'] as String),
  );

  @override
  UserStateLoaded copyWith({
    User? user,
    Address? lastKnownAddress,
    Role? role,
    Status? status,
  }) => _UserStateLoaded(
    user: user ?? this.user,
    lastKnownAddress: lastKnownAddress ?? this.lastKnownAddress,
    role: role ?? this.role,
    status: status ?? this.status,
  );

  @override
  Map<String, dynamic> toJson() => {
    'user': user.toJson(),
    'lastKnownAddress': lastKnownAddress.toJson(),
    'role': role.name,
    'status': status.name,
  };

  @override
  bool operator ==(Object other) =>
    identical(this, other) ||
    (other is _UserStateLoaded && other.user == user && other.lastKnownAddress == lastKnownAddress && other.role == role && other.status == status);

  @override
  int get hashCode => Object.hashAll([user, lastKnownAddress, role, status]);

  @override
  String toString() => 'UserStateLoaded(user: $user, lastKnownAddress: $lastKnownAddress, role: $role, status: $status)';
}

extension _$UserStateLoadedJsonExtension on UserStateLoaded {
  // ignore: unused_element
  static UserStateLoaded fromJson(Map<String, dynamic> json) =>
      _UserStateLoaded.fromJson(json);
}
