// GENERATED BY VELTRO — DO NOT EDIT
part of 'user_state_error.dart';

mixin _$UserStateError {
  String get errorCode;
  String? get errorMessage;

  UserStateError copyWith({String? errorCode, String? errorMessage, });
  Map<String, dynamic> toJson();

  @override
  String toString();
}

class _UserStateError with _$UserStateError implements UserStateError {
  @override final String errorCode;
  @override final String? errorMessage;

  const _UserStateError({
    required this.errorCode,
    this.errorMessage,
  });

  factory _UserStateError.fromJson(Map<String, dynamic> json) => _UserStateError(
    errorCode: json['errorCode'] as String,
    errorMessage: json['errorMessage'] as String?,
  );

  @override
  UserStateError copyWith({
    String? errorCode,
    String? errorMessage,
  }) => _UserStateError(
    errorCode: errorCode ?? this.errorCode,
    errorMessage: errorMessage ?? this.errorMessage,
  );

  @override
  Map<String, dynamic> toJson() => {
    'errorCode': errorCode,
    'errorMessage': errorMessage,
  };

  @override
  bool operator ==(Object other) =>
    identical(this, other) ||
    (other is _UserStateError && other.errorCode == errorCode && other.errorMessage == errorMessage);

  @override
  int get hashCode => Object.hashAll([errorCode, errorMessage]);

  @override
  String toString() => 'UserStateError(errorCode: $errorCode, errorMessage: $errorMessage)';
}

extension _$UserStateErrorJsonExtension on UserStateError {
  // ignore: unused_element
  static UserStateError fromJson(Map<String, dynamic> json) =>
      _UserStateError.fromJson(json);
}
