// GENERATED BY VELTRO — DO NOT EDIT
part of 'user_updated.dart';

mixin _$UserUpdated {
  User get user;
  Status get status;
  Role get role;

  UserUpdated copyWith({User? user, Status? status, Role? role, });
  Map<String, dynamic> toJson();

  @override
  String toString();
}

class _UserUpdated with _$UserUpdated implements UserUpdated {
  @override final User user;
  @override final Status status;
  @override final Role role;

  const _UserUpdated({
    required this.user,
    required this.status,
    required this.role,
  });

  factory _UserUpdated.fromJson(Map<String, dynamic> json) => _UserUpdated(
    user: User.fromJson(json['user'] as Map<String, dynamic>),
    status: Status.values.byName(json['status'] as String),
    role: Role.values.byName(json['role'] as String),
  );

  @override
  UserUpdated copyWith({
    User? user,
    Status? status,
    Role? role,
  }) => _UserUpdated(
    user: user ?? this.user,
    status: status ?? this.status,
    role: role ?? this.role,
  );

  @override
  Map<String, dynamic> toJson() => {
    'user': user.toJson(),
    'status': status.name,
    'role': role.name,
  };

  @override
  bool operator ==(Object other) =>
    identical(this, other) ||
    (other is _UserUpdated && other.user == user && other.status == status && other.role == role);

  @override
  int get hashCode => Object.hashAll([user, status, role]);

  @override
  String toString() => 'UserUpdated(user: $user, status: $status, role: $role)';
}

extension _$UserUpdatedJsonExtension on UserUpdated {
  // ignore: unused_element
  static UserUpdated fromJson(Map<String, dynamic> json) =>
      _UserUpdated.fromJson(json);
}
