// GENERATED BY VELTRO — DO NOT EDIT
part of 'user_requested.dart';

mixin _$UserRequested {
  String get userId;
  bool get forceReload;
  String? get correlationId;

  UserRequested copyWith({String? userId, bool? forceReload, String? correlationId, });
  Map<String, dynamic> toJson();

  @override
  String toString();
}

class _UserRequested with _$UserRequested implements UserRequested {
  @override final String userId;
  @override final bool forceReload;
  @override final String? correlationId;

  const _UserRequested({
    required this.userId,
    required this.forceReload,
    this.correlationId,
  });

  factory _UserRequested.fromJson(Map<String, dynamic> json) => _UserRequested(
    userId: json['userId'] as String,
    forceReload: json['forceReload'] as bool,
    correlationId: json['correlationId'] as String?,
  );

  @override
  UserRequested copyWith({
    String? userId,
    bool? forceReload,
    String? correlationId,
  }) => _UserRequested(
    userId: userId ?? this.userId,
    forceReload: forceReload ?? this.forceReload,
    correlationId: correlationId ?? this.correlationId,
  );

  @override
  Map<String, dynamic> toJson() => {
    'userId': userId,
    'forceReload': forceReload,
    'correlationId': correlationId,
  };

  @override
  bool operator ==(Object other) =>
    identical(this, other) ||
    (other is _UserRequested && other.userId == userId && other.forceReload == forceReload && other.correlationId == correlationId);

  @override
  int get hashCode => Object.hashAll([userId, forceReload, correlationId]);

  @override
  String toString() => 'UserRequested(userId: $userId, forceReload: $forceReload, correlationId: $correlationId)';
}

extension _$UserRequestedJsonExtension on UserRequested {
  // ignore: unused_element
  static UserRequested fromJson(Map<String, dynamic> json) =>
      _UserRequested.fromJson(json);
}
